services:
  kapil-test:
    image: nginx:alpine
    container_name: kapil-test
    restart: unless-stopped
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - caddy-net

  kapil-test-pb:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: kapil-test-pb
    restart: unless-stopped
    volumes:
      - ./pb_data:/pb_data
    networks:
      - caddy-net

networks:
  caddy-net:
    external: true
