#!/usr/bin/env python3
"""Builds the embedded PDF fonts for the shared PDF engine.

jsPDF's built-in Helvetica is Latin-1 only, so the rupee sign (U+20B9) cannot be
rendered by it. This script takes the Geist variable fonts already shipped with
the app (@fontsource-variable/geist), instantiates static Regular and Bold cuts,
merges the latin + latin-ext subsets (latin-ext carries the rupee glyph), strips
them down to the characters reports actually use, and writes them as base64 TTFs
into src/lib/exports/pdf-fonts.ts.

Usage (needs fonttools + brotli):
    python3 -m venv .venv && .venv/bin/pip install fonttools brotli
    .venv/bin/python scripts/build-pdf-fonts.py
"""
from __future__ import annotations

import base64
from io import BytesIO
from pathlib import Path

from fontTools import subset
from fontTools.merge import Merger
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

REPO = Path(__file__).resolve().parent.parent
GEIST_DIR = REPO / "node_modules/@fontsource-variable/geist/files"
OUT_TS = REPO / "src/lib/exports/pdf-fonts.ts"

# Basic Latin, Latin-1 punctuation/symbols, curly quotes/dashes, and the rupee sign.
KEEP_UNICODES = "U+0020-007E,U+00A0-00FF,U+2013-2014,U+2018-2019,U+201C-201D,U+2026,U+20B9"


def instantiate(path: Path, weight: int) -> TTFont:
    font = TTFont(path)
    instantiateVariableFont(font, {"wght": weight}, inplace=True)
    # Merger chokes on variable-font leftovers; the static instance no longer needs them.
    for table in ("STAT", "fvar", "gvar", "avar", "HVAR", "MVAR"):
        if table in font:
            del font[table]
    return font


def merge_subsets(fonts: list[TTFont]) -> TTFont:
    buffers = []
    for font in fonts:
        buffer = BytesIO()
        font.flavor = None  # write plain TTF, not woff2
        font.save(buffer)
        buffer.seek(0)
        buffers.append(buffer)
    return Merger().merge(buffers)


def subset_font(font: TTFont) -> bytes:
    options = subset.Options()
    options.flavor = None
    options.name_IDs = [1, 2, 3, 4, 6]
    options.layout_features = ["kern", "liga", "tnum"]
    subsetter = subset.Subsetter(options)
    subsetter.populate(unicodes=subset.parse_unicodes(KEEP_UNICODES))
    subsetter.subset(font)
    buffer = BytesIO()
    font.save(buffer)
    return buffer.getvalue()


def build_weight(weight: int) -> bytes:
    fonts = [
        instantiate(GEIST_DIR / "geist-latin-wght-normal.woff2", weight),
        instantiate(GEIST_DIR / "geist-latin-ext-wght-normal.woff2", weight),
    ]
    merged = merge_subsets(fonts)
    data = subset_font(merged)

    check = TTFont(BytesIO(data))
    cmap = check.getBestCmap()
    for codepoint, label in [(0x41, "A"), (0x39, "9"), (0x20B9, "rupee")]:
        if codepoint not in cmap:
            raise SystemExit(f"weight {weight}: missing {label} (U+{codepoint:04X}) after subsetting")
    return data


def main() -> None:
    regular = build_weight(400)
    bold = build_weight(700)
    OUT_TS.write_text(
        "// Generated by scripts/build-pdf-fonts.py — do not edit by hand.\n"
        "// Geist Regular/Bold (latin + latin-ext incl. the rupee sign) as base64 TTFs\n"
        "// for embedding into jsPDF documents. Loaded lazily with the PDF engine.\n\n"
        f"export const PDF_FONT_FAMILY = 'GeistPdf'\n\n"
        f"export const GEIST_PDF_REGULAR_B64 =\n  '{base64.b64encode(regular).decode()}'\n\n"
        f"export const GEIST_PDF_BOLD_B64 =\n  '{base64.b64encode(bold).decode()}'\n"
    )
    print(f"regular: {len(regular) / 1024:.1f} KB, bold: {len(bold) / 1024:.1f} KB")
    print(f"wrote {OUT_TS.relative_to(REPO)}")


if __name__ == "__main__":
    main()
