/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as PrintBillRouteImport } from './routes/print-bill'
import { Route as NewPaymentRouteImport } from './routes/new-payment'
import { Route as NewBillRouteImport } from './routes/new-bill'
import { Route as MonthlyReportRouteImport } from './routes/monthly-report'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CastingRouteImport } from './routes/casting'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BuyingRouteImport } from './routes/buying'
import { Route as BackupRouteImport } from './routes/backup'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CastingNewSessionRouteImport } from './routes/casting/new-session'
import { Route as CastingLogRouteImport } from './routes/casting/log'
import { Route as BuyingSuppliersRouteImport } from './routes/buying/suppliers'
import { Route as BuyingSupplierPaymentsRouteImport } from './routes/buying/supplier-payments'
import { Route as BuyingSupplierLedgerRouteImport } from './routes/buying/supplier-ledger'
import { Route as BuyingPurchaseLogsRouteImport } from './routes/buying/purchase-logs'
import { Route as BuyingNewPurchaseRouteImport } from './routes/buying/new-purchase'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintBillRoute = PrintBillRouteImport.update({
  id: '/print-bill',
  path: '/print-bill',
  getParentRoute: () => rootRouteImport,
} as any)
const NewPaymentRoute = NewPaymentRouteImport.update({
  id: '/new-payment',
  path: '/new-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const NewBillRoute = NewBillRouteImport.update({
  id: '/new-bill',
  path: '/new-bill',
  getParentRoute: () => rootRouteImport,
} as any)
const MonthlyReportRoute = MonthlyReportRouteImport.update({
  id: '/monthly-report',
  path: '/monthly-report',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CastingRoute = CastingRouteImport.update({
  id: '/casting',
  path: '/casting',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyingRoute = BuyingRouteImport.update({
  id: '/buying',
  path: '/buying',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupRoute = BackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CastingNewSessionRoute = CastingNewSessionRouteImport.update({
  id: '/new-session',
  path: '/new-session',
  getParentRoute: () => CastingRoute,
} as any)
const CastingLogRoute = CastingLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => CastingRoute,
} as any)
const BuyingSuppliersRoute = BuyingSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => BuyingRoute,
} as any)
const BuyingSupplierPaymentsRoute = BuyingSupplierPaymentsRouteImport.update({
  id: '/supplier-payments',
  path: '/supplier-payments',
  getParentRoute: () => BuyingRoute,
} as any)
const BuyingSupplierLedgerRoute = BuyingSupplierLedgerRouteImport.update({
  id: '/supplier-ledger',
  path: '/supplier-ledger',
  getParentRoute: () => BuyingRoute,
} as any)
const BuyingPurchaseLogsRoute = BuyingPurchaseLogsRouteImport.update({
  id: '/purchase-logs',
  path: '/purchase-logs',
  getParentRoute: () => BuyingRoute,
} as any)
const BuyingNewPurchaseRoute = BuyingNewPurchaseRouteImport.update({
  id: '/new-purchase',
  path: '/new-purchase',
  getParentRoute: () => BuyingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backup': typeof BackupRoute
  '/buying': typeof BuyingRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/casting': typeof CastingRouteWithChildren
  '/customers': typeof CustomersRoute
  '/items': typeof ItemsRoute
  '/ledger': typeof LedgerRoute
  '/monthly-report': typeof MonthlyReportRoute
  '/new-bill': typeof NewBillRoute
  '/new-payment': typeof NewPaymentRoute
  '/print-bill': typeof PrintBillRoute
  '/transactions': typeof TransactionsRoute
  '/buying/new-purchase': typeof BuyingNewPurchaseRoute
  '/buying/purchase-logs': typeof BuyingPurchaseLogsRoute
  '/buying/supplier-ledger': typeof BuyingSupplierLedgerRoute
  '/buying/supplier-payments': typeof BuyingSupplierPaymentsRoute
  '/buying/suppliers': typeof BuyingSuppliersRoute
  '/casting/log': typeof CastingLogRoute
  '/casting/new-session': typeof CastingNewSessionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backup': typeof BackupRoute
  '/buying': typeof BuyingRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/casting': typeof CastingRouteWithChildren
  '/customers': typeof CustomersRoute
  '/items': typeof ItemsRoute
  '/ledger': typeof LedgerRoute
  '/monthly-report': typeof MonthlyReportRoute
  '/new-bill': typeof NewBillRoute
  '/new-payment': typeof NewPaymentRoute
  '/print-bill': typeof PrintBillRoute
  '/transactions': typeof TransactionsRoute
  '/buying/new-purchase': typeof BuyingNewPurchaseRoute
  '/buying/purchase-logs': typeof BuyingPurchaseLogsRoute
  '/buying/supplier-ledger': typeof BuyingSupplierLedgerRoute
  '/buying/supplier-payments': typeof BuyingSupplierPaymentsRoute
  '/buying/suppliers': typeof BuyingSuppliersRoute
  '/casting/log': typeof CastingLogRoute
  '/casting/new-session': typeof CastingNewSessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backup': typeof BackupRoute
  '/buying': typeof BuyingRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/casting': typeof CastingRouteWithChildren
  '/customers': typeof CustomersRoute
  '/items': typeof ItemsRoute
  '/ledger': typeof LedgerRoute
  '/monthly-report': typeof MonthlyReportRoute
  '/new-bill': typeof NewBillRoute
  '/new-payment': typeof NewPaymentRoute
  '/print-bill': typeof PrintBillRoute
  '/transactions': typeof TransactionsRoute
  '/buying/new-purchase': typeof BuyingNewPurchaseRoute
  '/buying/purchase-logs': typeof BuyingPurchaseLogsRoute
  '/buying/supplier-ledger': typeof BuyingSupplierLedgerRoute
  '/buying/supplier-payments': typeof BuyingSupplierPaymentsRoute
  '/buying/suppliers': typeof BuyingSuppliersRoute
  '/casting/log': typeof CastingLogRoute
  '/casting/new-session': typeof CastingNewSessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backup'
    | '/buying'
    | '/calendar'
    | '/casting'
    | '/customers'
    | '/items'
    | '/ledger'
    | '/monthly-report'
    | '/new-bill'
    | '/new-payment'
    | '/print-bill'
    | '/transactions'
    | '/buying/new-purchase'
    | '/buying/purchase-logs'
    | '/buying/supplier-ledger'
    | '/buying/supplier-payments'
    | '/buying/suppliers'
    | '/casting/log'
    | '/casting/new-session'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backup'
    | '/buying'
    | '/calendar'
    | '/casting'
    | '/customers'
    | '/items'
    | '/ledger'
    | '/monthly-report'
    | '/new-bill'
    | '/new-payment'
    | '/print-bill'
    | '/transactions'
    | '/buying/new-purchase'
    | '/buying/purchase-logs'
    | '/buying/supplier-ledger'
    | '/buying/supplier-payments'
    | '/buying/suppliers'
    | '/casting/log'
    | '/casting/new-session'
  id:
    | '__root__'
    | '/'
    | '/backup'
    | '/buying'
    | '/calendar'
    | '/casting'
    | '/customers'
    | '/items'
    | '/ledger'
    | '/monthly-report'
    | '/new-bill'
    | '/new-payment'
    | '/print-bill'
    | '/transactions'
    | '/buying/new-purchase'
    | '/buying/purchase-logs'
    | '/buying/supplier-ledger'
    | '/buying/supplier-payments'
    | '/buying/suppliers'
    | '/casting/log'
    | '/casting/new-session'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackupRoute: typeof BackupRoute
  BuyingRoute: typeof BuyingRouteWithChildren
  CalendarRoute: typeof CalendarRoute
  CastingRoute: typeof CastingRouteWithChildren
  CustomersRoute: typeof CustomersRoute
  ItemsRoute: typeof ItemsRoute
  LedgerRoute: typeof LedgerRoute
  MonthlyReportRoute: typeof MonthlyReportRoute
  NewBillRoute: typeof NewBillRoute
  NewPaymentRoute: typeof NewPaymentRoute
  PrintBillRoute: typeof PrintBillRoute
  TransactionsRoute: typeof TransactionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print-bill': {
      id: '/print-bill'
      path: '/print-bill'
      fullPath: '/print-bill'
      preLoaderRoute: typeof PrintBillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-payment': {
      id: '/new-payment'
      path: '/new-payment'
      fullPath: '/new-payment'
      preLoaderRoute: typeof NewPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-bill': {
      id: '/new-bill'
      path: '/new-bill'
      fullPath: '/new-bill'
      preLoaderRoute: typeof NewBillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monthly-report': {
      id: '/monthly-report'
      path: '/monthly-report'
      fullPath: '/monthly-report'
      preLoaderRoute: typeof MonthlyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casting': {
      id: '/casting'
      path: '/casting'
      fullPath: '/casting'
      preLoaderRoute: typeof CastingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buying': {
      id: '/buying'
      path: '/buying'
      fullPath: '/buying'
      preLoaderRoute: typeof BuyingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup': {
      id: '/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof BackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casting/new-session': {
      id: '/casting/new-session'
      path: '/new-session'
      fullPath: '/casting/new-session'
      preLoaderRoute: typeof CastingNewSessionRouteImport
      parentRoute: typeof CastingRoute
    }
    '/casting/log': {
      id: '/casting/log'
      path: '/log'
      fullPath: '/casting/log'
      preLoaderRoute: typeof CastingLogRouteImport
      parentRoute: typeof CastingRoute
    }
    '/buying/suppliers': {
      id: '/buying/suppliers'
      path: '/suppliers'
      fullPath: '/buying/suppliers'
      preLoaderRoute: typeof BuyingSuppliersRouteImport
      parentRoute: typeof BuyingRoute
    }
    '/buying/supplier-payments': {
      id: '/buying/supplier-payments'
      path: '/supplier-payments'
      fullPath: '/buying/supplier-payments'
      preLoaderRoute: typeof BuyingSupplierPaymentsRouteImport
      parentRoute: typeof BuyingRoute
    }
    '/buying/supplier-ledger': {
      id: '/buying/supplier-ledger'
      path: '/supplier-ledger'
      fullPath: '/buying/supplier-ledger'
      preLoaderRoute: typeof BuyingSupplierLedgerRouteImport
      parentRoute: typeof BuyingRoute
    }
    '/buying/purchase-logs': {
      id: '/buying/purchase-logs'
      path: '/purchase-logs'
      fullPath: '/buying/purchase-logs'
      preLoaderRoute: typeof BuyingPurchaseLogsRouteImport
      parentRoute: typeof BuyingRoute
    }
    '/buying/new-purchase': {
      id: '/buying/new-purchase'
      path: '/new-purchase'
      fullPath: '/buying/new-purchase'
      preLoaderRoute: typeof BuyingNewPurchaseRouteImport
      parentRoute: typeof BuyingRoute
    }
  }
}

interface BuyingRouteChildren {
  BuyingNewPurchaseRoute: typeof BuyingNewPurchaseRoute
  BuyingPurchaseLogsRoute: typeof BuyingPurchaseLogsRoute
  BuyingSupplierLedgerRoute: typeof BuyingSupplierLedgerRoute
  BuyingSupplierPaymentsRoute: typeof BuyingSupplierPaymentsRoute
  BuyingSuppliersRoute: typeof BuyingSuppliersRoute
}

const BuyingRouteChildren: BuyingRouteChildren = {
  BuyingNewPurchaseRoute: BuyingNewPurchaseRoute,
  BuyingPurchaseLogsRoute: BuyingPurchaseLogsRoute,
  BuyingSupplierLedgerRoute: BuyingSupplierLedgerRoute,
  BuyingSupplierPaymentsRoute: BuyingSupplierPaymentsRoute,
  BuyingSuppliersRoute: BuyingSuppliersRoute,
}

const BuyingRouteWithChildren =
  BuyingRoute._addFileChildren(BuyingRouteChildren)

interface CastingRouteChildren {
  CastingLogRoute: typeof CastingLogRoute
  CastingNewSessionRoute: typeof CastingNewSessionRoute
}

const CastingRouteChildren: CastingRouteChildren = {
  CastingLogRoute: CastingLogRoute,
  CastingNewSessionRoute: CastingNewSessionRoute,
}

const CastingRouteWithChildren =
  CastingRoute._addFileChildren(CastingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackupRoute: BackupRoute,
  BuyingRoute: BuyingRouteWithChildren,
  CalendarRoute: CalendarRoute,
  CastingRoute: CastingRouteWithChildren,
  CustomersRoute: CustomersRoute,
  ItemsRoute: ItemsRoute,
  LedgerRoute: LedgerRoute,
  MonthlyReportRoute: MonthlyReportRoute,
  NewBillRoute: NewBillRoute,
  NewPaymentRoute: NewPaymentRoute,
  PrintBillRoute: PrintBillRoute,
  TransactionsRoute: TransactionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
